module.exports = [
  {
    id: Date.now(),
    item_name: 'AirPods',
    amount: 300,
    date: 'April 2 2022',
    from: 'Bob',
    category: 'Electronics',
    type: expense,
  },
  {
    id: Date.now(),
    item_name: 'Coffee',
    amount: 5,
    date: 'April 2 2022',
    from: 'Rachel',
    category: 'Drink',
    type: expense,
  },
  {
    id: Date.now(),
    item_name: 'Salary',
    amount: 2000,
    date: 'April 1 2022',
    from: 'Employer',
    category: 'Income',
    type: expense,
  },
  {
    id: Date.now(),
    item_name: 'Tax Payment',
    amount: -900,
    date: 'April 10 2022',
    from: 'IRS',
    category: 'Taxes',
    type: expense,
  },
  {
    id: Date.now(),
    item_name: '',
    amount: -200,
    date: 'April 1 2022',
    from: 'Rachel',
    category: 'Retirement',
    type: expense,
  },
  {
    id: Date.now(),
    item_name: 'Pension',
    date: 'April 5 2022',
    amount: -100,
    from: 'Employer',
    category: 'Savings',
    type: expense,
  },
  {
    id: Date.now(),
    item_name: 'Credit Card Payment',
    date: 'April 5 2022',
    amount: -100,
    from: 'Rachel',
    category: 'Bills',
    type: expense,
  },
  {
    id: Date.now(),
    item_name: 'Gift',
    date: 'June 10 2022',
    amount: 20,
    from: 'Aunt Tilda',
    category: 'Gift',
    type: income
  },

  {
    id: Date.now(),
    item_name: 'PetFood',
    date: 'April 3 2022',
    amount: 7,
    from: 'Rachel',
    category: 'PetFood',
    type: expense,
  },
];
