module.exports = [
  {
    id: Date.now(),
    item_name: 'AirPods',
    amount: 300,
    date: 'April 2 2022',
    from: 'Bob',
    category: 'Electronics',
    type: expense,
  },
  {
    id: Date.now(),
    item_name: 'Coffee',
    amount: 5,
    date: 'April 2 2022',
    from: 'Rachel',
    category: 'Food',
    type: expense,
  },
  {
    id: Date.now(),
    item_name: 'Pay',
    amount: 2000,
    date: 'April 1 2022',
    from: 'Boss',
    category: 'Salary',
    type: expense,
  },
  {
    id: Date.now(),
    item_name: 'IRS Tax Payment',
    amount: -900,
    date: 'April 10 2022',
    from: 'Rachel',
    category: 'Taxes',
    type: expense,
  },
  {
    id: Date.now(),
    item_name: '401k',
    amount: -200,
    date: 'April 1 2022',
    from: 'Rachel',
    category: 'Retirement',
    type: expense,
  },
  {
    id: Date.now(),
    item_name: 'Pension',
    date: 'April 5 2022',
    amount: -100,
    from: 'Rachel',
    category: 'Savings',
    type: expense,
  },
  {
    id: Date.now(),
    item_name: 'Credit Card Payment',
    date: 'April 5 2022',
    amount: -100,
    from: 'Rachel',
    category: 'Bills',
  },
  {
    id: Date.now(),
    item_name: 'Gift',
    date: 'June 10 2022',
    amount: 20,
    from: 'Aunt Tilda',
    category: 'Gift',
  },

  {
    id: Date.now(),
    item_name: 'Blue',
    date: 'April 3 2022',
    amount: -7,
    from: 'Rachel',
    category: 'Pet Food',
  },
];
